### ISSUE TITLE
Is this spec published somewhere?

### ISSUE THREAD

**Issue by Ms2ger** [WebAssembly/JS-BigInt-integration#18]

**Comment by littledan** [comment]
If someone wants to publish the JS API in gh-pages, it would probably be a good idea. You can use a CI to automate the build and deploy.

**Comment by xtuc** [comment]
@littledan I'm going to do it. I won't be able to setup CI however because I'm not admin here.

**Comment by littledan** [comment]
@xtuc You should have admin permissions now.

**Comment by xtuc** [comment]
Spec is now available https://webassembly.github.io/JS-BigInt-integration/js-api/index.html.

**Comment by littledan** [comment]
Please add a link to this from the README.
