### ISSUE TITLE
Propose to phase 4

### ISSUE THREAD

**Issue by Ms2ger** [WebAssembly/JS-BigInt-integration#32]
Entry requirements:

- [x] Two or more Web VMs implement the feature.
  - SpiderMonkey and V8 implement.
- [x] At least one toolchain implements the feature.
- [x] <del>The formalization and the reference interpreter are usually updated (though these two can be done as part of step 3 at the Working Group chair's discretion).</del>
- [x] Community Group has reached consensus in support of the feature.

**Comment by kripken** [comment]
For toolchain support in emscripten specifically we'll need to stop "legalizing" i64s into pairs of i32s, and handle the receiving of bigints in the JS support code. I hope to look into that soon.

**Comment by xtuc** [comment]
`wasm-bindgen` allows the transformation of Rust's u64 and i64 to JS' BigInt https://github.com/rustwasm/wasm-bindgen/pull/188/files.

**Comment by CryZe** [comment]
> `wasm-bindgen` allows the transformation of Rust's u64 and i64 to JS' BigInt https://github.com/rustwasm/wasm-bindgen/pull/188/files.

That's more of a workaround though, rather than implementing the proposal. So just like emscripten, it would need to be rewritten.

**Comment by xtuc** [comment]
@CryZe you are right, I misread the PR. `wasm-bindgen` also lowers them

**Comment by kripken** [comment]
The emscripten work for BigInt has landed: https://github.com/emscripten-core/emscripten/pull/10860 

That uses BigInts on wasm imports and exports of i64s, so it changes the FFI between wasm and JS. (So far we don't use `BigInt64Array` as that isn't on the FFI boundary, and the benefit to us isn't clear). Tested with v8, everything looks good.

**Comment by Ms2ger** [comment]
CG approved in the 2020-05-12 meeting.
